repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.11.1"
  hooks:
    - id: mypy
      exclude: "noxfile.py|cli.py"
      args: [ --ignore-missing-imports, --follow-imports=skip, --strict, --strict-optional ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
