"""Utility functions for PheWeb."""

import pathlib
import sqlite3

import pandas as pd
from fpdf import FPDF


def convert_tsv_gz_to_sqlite(data_path: pathlib.Path) -> pathlib.Path:
    """Convert a TSV file to a SQLite database.

    Specifically meant for matrix.tsv.gz generated by PheWeb which have the following columns:
    - #chrom
    - pos
    - ref
    - alt
    - rsids
    - nearest_genes
    - pval@1-3-Methylhistidine
    - beta@1-3-Methylhistidine
    - maf@1-3-Methylhistidine
    - pval@creatine
    - beta@creatine
    - maf@creatine
    - ...

    Resulting SQLite database will allow for easy querying of the data TODO
    """
    sqlite_path = data_path.with_suffix(".sqlite")

    df = pd.read_csv(data_path, sep="\t")

    # Melting the data to long format
    id_cols = ["#chrom", "pos", "ref", "alt", "rsids", "nearest_genes"]
    pval_cols = [c for c in df.columns if "pval@" in c]
    pval_renames = {c: c.replace("pval@", "") for c in pval_cols}

    long_df = (
        df[id_cols + pval_cols]
        .rename(columns=pval_renames)
        .melt(
            id_vars=id_cols,
            var_name="phenotype",
            value_name="pval",
        )
    )

    beta_cols = [c for c in df.columns if "beta@" in c]
    beta_renames = {c: c.replace("beta@", "") for c in beta_cols}

    long_df["beta"] = (
        df[id_cols + beta_cols]
        .rename(columns=beta_renames)
        .melt(
            id_vars=id_cols,
            var_name="phenotype",
            value_name="beta",
        )["beta"]
    )

    maf_cols = [c for c in df.columns if "maf@" in c]
    maf_renames = {c: c.replace("maf@", "") for c in maf_cols}

    long_df["maf"] = (
        df[id_cols + maf_cols]
        .rename(columns=maf_renames)
        .melt(
            id_vars=id_cols,
            var_name="phenotype",
            value_name="maf",
        )["maf"]
    )

    try:
        conn = sqlite3.connect(sqlite_path)
        long_df.to_sql(name=data_path.stem, con=conn, if_exists="replace", index=False)
        conn.close()
    except Exception as e:
        sqlite_path.unlink()
        raise e

    return sqlite_path


def convert_tsv_gz_to_normalized_sqlite(data_path: pathlib.Path) -> pathlib.Path:
    """Convert a TSV file to a normalized SQLite database.

    Args:
    ----
        data_path: Path to the TSV file with columns:
            - #chrom
            - pos
            - ref
            - alt
            - rsids
            - nearest_genes
            - pval@1-3-Methylhistidine
            - beta@1-3-Methylhistidine
            - maf@1-3-Methylhistidine
            - pval@creatine
            - beta@creatine
            - maf@creatine
            - ...

    Returns:
    -------
        Path to the SQLite database.

    Resulting SQLite database will have the following tables:
    - variant
    - phenotype
    - measurement
    - annotation

    """
    sqlite_path = data_path.with_suffix(".normalized.sqlite")

    conn = sqlite3.connect(sqlite_path)
    conn.execute("PRAGMA foreign_keys = ON")
    cursor = conn.cursor()

    # Create tables
    cursor.execute(
        """
        CREATE TABLE variant (
            id INTEGER PRIMARY KEY,
            chrom TEXT,
            pos INTEGER,
            ref CHAR,
            alt CHAR,
            rsids TEXT
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE phenotype (
            id INTEGER PRIMARY KEY,
            name TEXT
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE measurement (
            variant_id INTEGER,
            phenotype_id INTEGER,
            pval REAL,
            beta REAL,
            maf REAL,
            FOREIGN KEY (variant_id) REFERENCES variant(id),
            FOREIGN KEY (phenotype_id) REFERENCES phenotype(id)
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE annotation (
            chrom TEXT,
            start INTEGER,
            end INTEGER,
            name TEXT
        )
        """
    )

    # Insert data
    df = pd.read_csv(data_path, sep="\t")

    phenotypes = set(c.split("@")[1] for c in df.columns if "@" in c)

    for phenotype in phenotypes:
        cursor.execute("INSERT INTO phenotype (name) VALUES (?)", (phenotype,))

    for _, row in df.iterrows():
        cursor.execute(
            "INSERT INTO variant (chrom, pos, ref, alt, rsids) VALUES (?, ?, ?, ?, ?)",
            (row["#chrom"], row["pos"], row["ref"], row["alt"], row["rsids"]),
        )
        variant_id = cursor.lastrowid

        for phenotype in phenotypes:
            cursor.execute(
                "INSERT INTO measurement (variant_id, phenotype_id, pval, beta, maf) VALUES (?, ?, ?, ?, ?)",
                (
                    variant_id,
                    cursor.execute(
                        "SELECT id FROM phenotype WHERE name = ?", (phenotype,)
                    ).fetchone()[0],
                    row[f"pval@{phenotype}"],
                    row[f"beta@{phenotype}"],
                    row[f"maf@{phenotype}"],
                ),
            )

    conn.commit()

    cursor.execute("VACUUM")
    conn.close()

    return sqlite_path


def write_pdf_from_matrix(data_path: pathlib.Path) -> pathlib.Path:
    """Write a PDF file from a Matrix TSV GZ file.

    Args:
    ----
        data_path: Path to the TSV file with columns:
            - #chrom
            - pos
            - ref
            - alt
            - rsids
            - nearest_genes
            - pval@1-3-Methylhistidine
            - beta@1-3-Methylhistidine
            - maf@1-3-Methylhistidine
            - pval@creatine
            - beta@creatine
            - maf@creatine
            - ...

    Returns:
    -------
        Path to the PDF file.

    """
    df = pd.read_csv(data_path, sep="\t")
    phenotypes = set(c.split("@")[1] for c in df.columns if "@" in c)

    pdf_path = data_path.with_suffix(".pdf")

    pdf = FPDF()
    pdf.set_font("helvetica", size=14)
    # Table of phenotypes
    pdf.add_page()
    with pdf.table() as table:
        for phenotype in phenotypes:
            row = table.row()
            row.cell(phenotype)

    # Pages of Manhattan plots (TODO just repeating the same PNG for now)
    for phenotype in phenotypes:
        pdf.add_page()
        pdf.cell(200, 10, f"Manhattan plot for {phenotype}", ln=True)
        pdf.image("example_manhattan.png", x=10, y=20, w=180)

    # TODO figure out how to add links
    link = pdf.add_link(page=1)
    pdf.cell(text="Internal link to first page", border=1, link=link)

    pdf.output(pdf_path)

    return pdf_path
